### ISSUE TITLE
Remove the unused dependency on pytest-virtualenv

### ISSUE THREAD

**Issue by hrnciar** [pyscaffold/configupdater#114]
Hello,

I don't see any usage of pytest-virtualenv in the code base, I think it can be removed. The tests run successfully without it. 

https://github.com/pyscaffold/configupdater/blob/229dcd61127d14baa7d6124937aee0c169a64670/setup.cfg#L68

**Comment by FlorianWilhelm** [comment]
Thank you @hrnciar :-) Do you want to provide a little PR?
