### ISSUE TITLE
Method whereby you can convert sections into dictionary structure

### ISSUE THREAD

**Issue by k5map** [pyscaffold/configupdater#116]
## Describe your use-case
As I have with using ConfigParser, I can take a section and convert it to a dictionary.  Then I pass this dict value to different functions within my program.

## Describe the solution you would like to see for your use-case
I can retrieve a list of keys via list(updater[section].keys() but am unable to enumerate the values without getting the "<Option:" string for each value.

**Comment by abravalheri** [comment]
Hi @k5map , have you tried https://configupdater.readthedocs.io/en/latest/api.html#configupdater.ConfigUpdater.to_dict?

**Comment by k5map** [comment]
@abravalheri ... that was the missing piece!  This does exactly what I need, thanks for the info
