### ISSUE TITLE
Version on pypi seems out of date

### ISSUE THREAD

**Issue by typonaut** [pyscaffold/configupdater#130]
The version of configupdater on pypi seems to be significantly older than the code in this repository, most obviously the current pypi version will not allow the input ```Options.set_values(… prepend_newline=False)```.

Are we awaiting an update, or is there some issue?

**Comment by FlorianWilhelm** [comment]
Hi @typonaut, yes you are absolutely right. Sorry for the long delay.

@abravalheri: Should we merge your PR #127 now and make a new final release `3.2`? I can do that if you agree.

**Comment by abravalheri** [comment]
Sorry for the lack of responsiveness  @FlorianWilhelm. Yes that would be great. Please feel free to go ahead.

**Comment by FlorianWilhelm** [comment]
@typonaut: it's released :-)
