### ISSUE TITLE
Recheck the whole API for consistency

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/configupdater#19]
"There are only two hard things in Computer Science: cache invalidation and naming things". Since ConfigUpdater doesn't make use of the former, we should focus on the latter ;-)
There is surely potential to improve here, e.g. 
1. `Container` has a `structure` holding `Block` objects. Should it be rather named `blocks` to make it clearer?
2. From ConfigParser we "inherited" several methods containing the word `items` but on the other hand we also have many `blocks` methods. Is this always consistent and do `items` only return strings and values like in a dictionary versus `Block` objects in case of `blocks` methods? 
3. ...

**Comment by abravalheri** [comment]
I think this is very much related to the problems I found when adding type hints in #23...

**Comment by FlorianWilhelm** [comment]
PR #28 is merged but let me recheck the source code again when working on #25 until we close this.

**Comment by FlorianWilhelm** [comment]
This is also done by the latest reorganizations and especially the introduction of typing. Thanks, @abravalheri for that.
