### ISSUE TITLE
Logo proposal 😝 

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/configupdater#29]
During the weekend, I was playing around with ConfigUpdater so I decided to draw something:

![configupdater](https://user-images.githubusercontent.com/320755/121915315-02407a80-cd2b-11eb-8eb8-9fee022f42be.png)

It would be nice once we update the docs (maybe even using the same theme as PyScaffold uses now), to have a nice image.

I have used the opensource [Monoid typeface](https://github.com/larsenwork/monoid) (Andreas Larsen and contributors, 2015).
The colors used are:
```
accent: #008c70 (teal-ish)
pure black: #000000
pure white: #FFFFFF
30% gray: #b3b3b3 (box shadow)
```

I have the SVG files available here if that is interesting for the project 😄

**Comment by FlorianWilhelm** [comment]
It looks fantastic! Feel free to add the svg to the docs as in PyScaffold itself and use the logo wherever you see fit :-)

**Comment by abravalheri** [comment]
Thank you very much @FlorianWilhelm.

At some point I will take some time to tackle #17 and #18, and then it would be nice to include the image to the docs.
For the time being I will just add them to the repo so they are available.
