### ISSUE TITLE
Case of options is lost when using file

### ISSUE THREAD

**Issue by patrick-g2** [pyscaffold/configupdater#7]
Hi,
The section Feature in the doc says :
* the original case of sections and keys are kept,

That's no true for keys (option in the code).
When reading file, the case of all keys is changed to lower case (line 789).

Removing all the calls to optionxform() in configupdater.py seems to do the job.
They are 6 of them :
 configupdater.py:386: # option = self._container.optionxform(option)
configupdater.py:789: # optname = self.optionxform(optname.rstrip())
configupdater.py:972: # option = self.optionxform(option)
configupdater.py:1012: #option = self.optionxform(option)
configupdater.py:1027: # option = self.optionxform(option)
configupdater.py:1048: # option = self.optionxform(option)

Another way would be to transform optionxform() in a do nothing function (maybe with an option in `configupdater.__init__()`)
configupdater.py:639: def optionxform(self, optionstr):

I haven't tested updating or writing file yet.
 
Regards

**Comment by FlorianWilhelm** [comment]
Hi @patrick-g2, thanks for pointing that out. I haven't tested it yet but there might be a difference in what you take as key to access a value (here lower case makes sense as a convention) and how it is written in the end. It's been a while since I wrote the package but as far as I remember the original strings of the keys are kept. Could you check what happens if you write the file back? Nevertheless, I haven't found any unit test that actually checks it. Do you want to provide one?

**Comment by patrick-g2** [comment]
Hi @FlorianWilhelm,
Thank for your quick answer.
I tested an update of the file:
* Options which value is modified are written in lower case, unmodified ones are left as they are. That seems normal as keys are stored in lowercase (see output of configupdater.options() ).
* New keys are saved with their cases unchanged (i.e. mixed gives mixed).

Applying corrections mention in first post allows to save changed keys with their cases unmodified.

>  (here lower case makes sense as a convention)
Well, a strange convention which is only true for key, not section name :).
But it's true that Configparser do so by default. The doc. states that doing 
`cfgparser = ConfigParser()`
`cfgparser.optionxform = str`
would make option names case sensitive.

During my test I also found another bug.
`Add_after` method only works well the first time it is used. Subsequent calls always use the same fixed index.
It seems that `idx = self._container.structure.index(self)` can't return the index of a newly created option, only the index of  an option which has been created during the reading of file. But it may be more complex than that.

I'm a kind of newbie in Python, I have never used pytest or other test framework, so sorry no unit test. But I join a minimal example file which shows the two problems.
- test1 shows key case problem
- test2 shows the add_after problem. 
If you comment out (or in) the line 61 `        self.upd['Macros']['multiclickdelay'].add_before.option('License', 'GPL')
` in test1 you will see that the "fixed" index is not always the last used one.

The two tests are called in sequence, but can be run independently.
 
Don't forget to restore the Sequences.ini file before each run of the tests they mangle the config file.

Minimal test files :
[Test.tar.gz](https://github.com/pyscaffold/configupdater/files/4912746/Test.tar.gz)

**Comment by patrick-g2** [comment]
Hi @FlorianWilhelm,
One more point about case.
The fact that option names (keys) are stored in lowercase permits to create invalid cfg file.
Suppose the file contains a option `MyKey = 1`. After loading the file, the option is stored as  `mykey = 1`.
Now, the app try tochange the value: `updt[MySec][MyKey].value = 2` (note the case).
As MyKey is different from mykey, a new option is created, stored as `MyKey = 2` (note the case again).
Update the file, it contains : 
`[MySec]`
`MyKey = 1` (case preserved because the option is unmodified)
`MyKey = 2`
This new file is clearly invalid for ConfigUpdater and ConfigParser.

**Comment by patrick-g2** [comment]
I tried to find tracks for the "add_after" behavior but without success for now.
I added some debug print to the test file I sent you.
How is it possible that several options of the same section have the same index ?
When the first option is added add_after() finds an index of "10" and calls BlockBuilder with a value of "11" (I put a print in add_after()). But after the add finishes, the index of the new option is "1" (if the option adding of test 1 IS NOT commented out) and 12 (if the option adding of test 1 IS commented out).
After that all the options added get the same index 1 or 12.
Test file with the new prints:
[Test.zip](https://github.com/pyscaffold/configupdater/files/4919230/Test.zip)

**Comment by patrick-g2** [comment]
I forget to say: I use Python 3.7.6. on Linux kernel 5.6.14  64 bits.

**Comment by patrick-g2** [comment]
Oh, just saw that you committed some fixes. I will try them.

**Comment by FlorianWilhelm** [comment]
@patrick-g2 Thanks for that reminder and your test files as they helped a lot in writing unit tests. Have you tried the latest commit if it works for you?

**Comment by patrick-g2** [comment]
Hi @FlorianWilhelm,
Many thanks for the quick fixes. 
I just try the latest commit.
* The use of all types of case in key names seems to work seamlessly, with case preservation when updating the file.
* add_after and add_before work as expected.
* The last problem (creation multiple occurrences of the same option with add_after and add_before -  https://github.com/pyscaffold/configupdater/issues/7#issuecomment-658185939) is still present.

As an example is better than a long speech, I join a test file which show the facts.
[Test_2.zip](https://github.com/pyscaffold/configupdater/files/4924041/Test_2.zip)

**Comment by patrick-g2** [comment]
Just tried the version 1.1.
Everything is OK, Test.zip and Test2.zip (after adding try: except: of course) work as expected.
Many thanks for all these quick fixes.

**Comment by FlorianWilhelm** [comment]
Hi @patrick-g2, thanks for posting this issue and providing so many examples to reproduce the bugs, this helped a lot! 
I just uploaded the version `1.1` to pypi. This was a great teamwork, vive l'amitié franco-allemande 🇫🇷 🇩🇪
