### ISSUE TITLE
Indentation in multiline values is lost when modifying `value`

### ISSUE THREAD

**Issue by jwodder** [pyscaffold/configupdater#87]
Let the contents of the file `setup.cfg` be as follows:

```ini
[metadata]
classifiers =
    Development Status :: 3 - Alpha
    #Development Status :: 4 - Beta
    #Development Status :: 5 - Production/Stable
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy
    License :: OSI Approved :: MIT License
```

Then:

```
>>> from configupdater import ConfigUpdater
>>> cfg = ConfigUpdater().read("setup.cfg")
>>> print(str(cfg))
[metadata]
classifiers =
    Development Status :: 3 - Alpha
    #Development Status :: 4 - Beta
    #Development Status :: 5 - Production/Stable
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy
    License :: OSI Approved :: MIT License

>>> print(cfg["metadata"]["classifiers"].value)

Development Status :: 3 - Alpha
#Development Status :: 4 - Beta
#Development Status :: 5 - Production/Stable
Programming Language :: Python :: 3 :: Only
Programming Language :: Python :: 3
Programming Language :: Python :: Implementation :: CPython
Programming Language :: Python :: Implementation :: PyPy
License :: OSI Approved :: MIT License
>>> cfg["metadata"]["classifiers"].value += "\nTopic :: Utilities"
>>> print(cfg["metadata"]["classifiers"].value)

Development Status :: 3 - Alpha
#Development Status :: 4 - Beta
#Development Status :: 5 - Production/Stable
Programming Language :: Python :: 3 :: Only
Programming Language :: Python :: 3
Programming Language :: Python :: Implementation :: CPython
Programming Language :: Python :: Implementation :: PyPy
License :: OSI Approved :: MIT License
Topic :: Utilities
>>> print(str(cfg))
[metadata]
classifiers =
Development Status :: 3 - Alpha
#Development Status :: 4 - Beta
#Development Status :: 5 - Production/Stable
Programming Language :: Python :: 3 :: Only
Programming Language :: Python :: 3
Programming Language :: Python :: Implementation :: CPython
Programming Language :: Python :: Implementation :: PyPy
License :: OSI Approved :: MIT License
Topic :: Utilities

>>> cfg.update_file()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-756f8f491897ace/lib/python3.9/site-packages/configupdater/configupdater.py", line 180, in update_file
    self.validate_format()
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-756f8f491897ace/lib/python3.9/site-packages/configupdater/configupdater.py", line 195, in validate_format
    return super().validate_format(**{**self._parser_opts, **kwargs})
  File "/Users/jwodder/.local/virtualenvwrapper/venvs/tmp-756f8f491897ace/lib/python3.9/site-packages/configupdater/document.py", line 103, in validate_format
    parser.read_string(str(self))
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 723, in read_string
    self.read_file(sfile, source)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 1096, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '<string>' [line  7]: option 'programming language' in section 'metadata' already exists
```

Observe that the option's value is returned with leading indentation stripped, though something remembers that the indentation is there, as seen when stringifying `cfg`.  However, when the value is modified, all memory of the indentation is lost, leading to a validation error when trying to save the updated file.

## Versions and main components

* ConfigUpdater Version: 3.0.1
* Python Version: 3.9.10
* Operating system: macOS 11.6
* How did you install ConfigUpdater: pip

**Comment by FlorianWilhelm** [comment]
Thanks, @jwodder for reporting this! This is definitively a bug.

**Comment by FlorianWilhelm** [comment]
Hm... I have to correct myself. When reading `cfg["metadata"]["classifiers"].value` the leading whitespaces are stripped which makes sense. By using the append operator `+=` you are overwriting the internally indented value with unintended ones, which leads to this strange behavior. 

What you need to do is this:
```
new_classifiers = updater["metadata"]["classifiers"].value.strip().split('\n') + ["Topic :: Utilities"]
updater["metadata"]["classifiers"].set_values(new_classifiers)
```

I see that this is a bit complicated. Another possibility for us would be to offer an attribute `raw_value` that returns the implicit representation, which includes the indentation. In this case `cfg["metadata"]["classifiers"].raw_value += "\nTopic :: Utilities"` would work. What do you think @abravalheri?

At this point, we clearly see that the compatibility to `ConfigUpdater` holds us back but I still think it is important.

**Comment by abravalheri** [comment]
@FlorianWilhelm if we go for the `raw_value` approach, then I think the best would be disallowing setting `value` directly. This would prevent the public API to be used to reach an invalid internal state...

Otherwise we also have some other approaches when executing `value +=`:
- Check if the value is multi-line and error with a message asking users to use `set_values` instead **OR**
- Check if all lines in the new value are indented, otherwise indent them.

**Comment by FlorianWilhelm** [comment]
Do you think it is possible to check for `+=` easily? Right now `value` is served as a property, i.e
```python
@property
def value(self) -> Optional[str]:
    self._join_multiline_value()
    return self._value
```
as `self._value` is returned the `+=` operator will operate directly on `self._value` which is a normal list. Is there an easy way to return an immutable list? I could construct my own list subtype but I guess that's a bit of an overkill. Hm... but maybe that is the best way to go.

**Comment by abravalheri** [comment]
> as `self._value` is returned the `+=` operator will operate directly on `self._value` which is a normal string. Is there an easy way to return an actual immutable string? I could construct my own string subtype but I guess that's a bit of an overkill. Hm... but maybe that is the only way to go.

Can't we just skip the `@value.setter` and instead replace it with a `set_raw_value(value)` function?
If there is no setter, Python will complain about the `+=` method with an `AttributeError: can't set attribute`...

**Comment by FlorianWilhelm** [comment]
Wow, same second comment!

Okay, then your solution above should work. So we would do:

1. Check if `@value.setter` is called on a multi-line attribute:
   a. If it is multiline, we error and tell the user to use `set_values` instead.
   b. if it is not, we just overwrite as before. (This keeps users happy for non-multiline changes)
2. We provide also a new method `append` that in case of multiline appends with the right indentation and takes care of `\n`s.

**Comment by abravalheri** [comment]
Yes that sounds good!

**Comment by FlorianWilhelm** [comment]
@jwodder. We just released v3.1 that addresses this issue. Could you give us some feedback and then close this issue if it is resolved? Thansk.

**Comment by jwodder** [comment]
@FlorianWilhelm The only problem I see is that the CHANGELOG (and commit message) refers to a `to_list()` method, whereas the method is actually named `as_list()`.

**Comment by FlorianWilhelm** [comment]
Arg, good point! I'll fix this so it will in the next release.
