### ISSUE TITLE
Indentation of section name isn't always preserved

### ISSUE THREAD

**Issue by Delgan** [pyscaffold/configupdater#92]
## Description of your problem

**Please provide a minimal, self-contained, and reproducible example.**
```python
import configupdater

cfg = """
[You can use comments]
# like this
; or this

# By default only in an empty line.
# Inline comments can be harmful because they prevent users
# from using the delimiting characters as parts of values.
# That being said, this can be customized.

    [Sections Can Be Indented]
        can_values_be_as_well = True
        does_that_mean_anything_special = False
        purpose = formatting for readability
        multiline_values = are
            handled just fine as
            long as they are indented
            deeper than the first line
            of a value
        # Did I mention we can indent comments, too?
"""


updater = configupdater.ConfigUpdater()
updater.read_string(cfg)
print(updater)
```

**Please provide the full traceback.**
N/A

**Please provide any additional information below.**
Hi!

So I was comparing `configupdater` against `configparser` using [some examples from the documentation](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure) and I noticed the above section lose it's indentation when parsed. It results with:

```ini
[You can use comments]
# like this
; or this

# By default only in an empty line.
# Inline comments can be harmful because they prevent users
# from using the delimiting characters as parts of values.
# That being said, this can be customized.

[Sections Can Be Indented]
        can_values_be_as_well = True
        does_that_mean_anything_special = False
        purpose = formatting for readability
        multiline_values = are
            handled just fine as
            long as they are indented
            deeper than the first line
            of a value
        # Did I mention we can indent comments, too?
```

It happens because the `[You can use comments]` section is empty (except for the comments).

Not a big deal, though. ;)

## Versions and main components

* ConfigUpdater Version: 3.1
* Python Version: 3.10.5
* Operating system: Arch Linux
* How did you install ConfigUpdater: pip

**Comment by FlorianWilhelm** [comment]
@Delgan, thanks for posting this issue. It really wasn't expecting that after all that years still subtle bugs show up. 

Would you be interested in providing a PR?

**Comment by Delgan** [comment]
@FlorianWilhelm Sure why not. I opened #93. ;)
